# Generated by Django 3.0.3 on 2020-02-22 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(null=True)),
                ('level', models.IntegerField(choices=[(1, 'Pre_swim'), (2, 'Begginers'), (3, 'Advanced'), (4, 'Competative')])),
                ('age_group', models.IntegerField(choices=[(1, '5-7'), (2, '8-12'), (3, '13-18'), (4, '18+')])),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='swimming.Coach')),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('birth_date', models.DateField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainees', to='swimming.Group')),
            ],
        ),
    ]
