# Generated by Django 3.0.3 on 2020-02-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminslot',
            name='title',
            field=models.CharField(default='hagit', max_length=200),
            preserve_default=False,
        ),
    ]
